version: "3.8"

services:
  metabase-db:
    image: postgres:17
    container_name: metabase-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${MB_DB_NAME}
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - metabase-db-data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    depends_on:
      - metabase-db
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: metabase-db
      MB_DB_PORT: 5432
      MB_DB_DBNAME: ${MB_DB_NAME}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m"
        # --- AUTO SETUP ---
      MB_SETUP_TOKEN: "setup123"           # qualquer string serve
      MB_EMAIL_SMTP_HOST: ""                # evita que ele pe√ßa SMTP
      MB_EMAIL_SMTP_PORT: ""
      MB_EMAIL_FROM_ADDRESS: ""
      MB_ANON_TRACKING_ENABLED: false
      MB_ENABLE_PUBLIC_SHARING: false
      MB_SETUP_ADMIN_EMAIL: "admin@example.com"
      MB_SETUP_ADMIN_PASSWORD: "admin123"
      MB_SETUP_ADMIN_FIRST_NAME: "Admin"
      MB_SETUP_ADMIN_LAST_NAME: "User"

volumes:
  metabase-db-data:
